name: Deploy ECR Staging

on:
  workflow_run:
    workflows:
      - Test
    branches:
      - develop
    types:
      - completed
  workflow_dispatch:

env:
  DOCKER_REGISTRY_HOST: ${{ secrets.ECR_REGISTRY_HOST }}
  DOCKER_IMAGE: ${{ secrets.STAGING_ECR_REPO }}
  ECS_CLUSTER: ${{ secrets.STAGING_ECS_CLUSTER }}
  ECS_SERVICE: ${{ secrets.STAGING_ECS_SERVICE }}
  BRANCH_TAG: latest

jobs:
  deploy:
    name: Deploy to ECR Staging
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - uses: actions/checkout@v2.3.4

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: bin/docker-prepare && docker-compose build

      - name: Push to ECR
        run: docker push $DOCKER_REGISTRY_HOST/$DOCKER_IMAGE:$BRANCH_TAG
